include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false  
    # Experimental and there are lots of false positives
    specify_nonobvious_property_types: false